### ISSUE TITLE
Usage in Production

### ISSUE THREAD

**Issue by asgoel** [xirsys/xturn#2]
How production ready is `xturn`? What are key features that you see as missing in order to make this production ready?

**Comment by Lazarus404** [comment]
Hi Asgoel,

As a starting point for a WebRTC project, it is production ready.  There are some missing features, such as IPv6 support, that may be an issue for some people, but XTurn will handle STUN and TURN for UDP and TCP (both secure and insecure) and will work great.

My perspective on XTurn in production is that it's a great beginning for something bigger.  If you want a malleable STUN/TURN server that you can add to and incorporate into a bigger picture, then I believe XTurn is perfect.  It's also a great resource to learn and understand how TURN servers work and for debugging WebRTC applications.  However, if all you need is a TURN server and you do NOT plan on doing anything to it, you would probably be better off using CoTURN, which is a more complete TURN server and caters for many more RFC specifications.

I hope this helps?

**Comment by asgoel** [comment]
@Lazarus404 definitely helps, thanks! Is there documentation of the various portions of the codebase in case we did want to extend it?

**Comment by Lazarus404** [comment]
It's definitely on our roadmap.  XTurn isn't a high priority at the moment, as it's not funded.  We were hoping it would generate a lot of interest in order to facilitate funding, but we haven't marketed it much, yet.  Since Millicast was launched, we have diverted most of our remaining resources to that.

However, I am giving a talk in July and using XTurn as the talking point.  I have a list of things I need to complete before that date comes :-)

**Comment by Lazarus404** [comment]
Hi @asgoel.  I'm going to close this issue, as it's not an actual issue :-)  However, please do feel free to re-open if you have further questions, as it's a good space to keep these.
